<template>
    <div class="loadingio-spinner-interwind-pslq5rbgr8">
        <div class="ldio-sn8z9znbf4c">
            <div>
                <div>
                    <div>
                        <div></div>
                    </div>
                </div>
                <div>
                    <div>
                        <div></div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</template>

<script lang="ts">
import { defineComponent } from "@vue/composition-api";
export default defineComponent({
    name: "Spinner",
    props: {},

    setup(props, content) {
        return {};
    },
});
</script>

<style type="text/css" scoped>
@keyframes ldio-sn8z9znbf4c-r {
    0%,
    100% {
        animation-timing-function: cubic-bezier(0.2 0 0.8 0.8);
    }
    50% {
        animation-timing-function: cubic-bezier(0.2 0.2 0.8 1);
    }
    0% {
        transform: rotate(0deg);
    }
    50% {
        transform: rotate(180deg);
    }
    100% {
        transform: rotate(360deg);
    }
}
@keyframes ldio-sn8z9znbf4c-s {
    0%,
    100% {
        animation-timing-function: cubic-bezier(0.2 0 0.8 0.8);
    }
    50% {
        animation-timing-function: cubic-bezier(0.2 0.2 0.8 1);
    }
    0% {
        transform: translate(-15px, -15px) scale(0);
    }
    50% {
        transform: translate(-15px, -15px) scale(1);
    }
    100% {
        transform: translate(-15px, -15px) scale(0);
    }
}
.ldio-sn8z9znbf4c > div {
    transform: translate(0px, -7.5px);
}
.ldio-sn8z9znbf4c > div > div {
    animation: ldio-sn8z9znbf4c-r 1s linear infinite;
    transform-origin: 50px 50px;
}
.ldio-sn8z9znbf4c > div > div > div {
    position: absolute;
    transform: translate(50px, 41px);
}
.ldio-sn8z9znbf4c > div > div > div > div {
    width: 30px;
    height: 30px;
    border-radius: 50%;
    background: #fe718d;
    animation: ldio-sn8z9znbf4c-s 1s linear infinite;
}
.ldio-sn8z9znbf4c > div > div:last-child {
    animation-delay: -0.5s;
}
.ldio-sn8z9znbf4c > div > div:last-child > div > div {
    animation-delay: -0.5s;
    background: #46dff0;
}
.loadingio-spinner-interwind-pslq5rbgr8 {
    width: 56px;
    height: 56px;
    display: inline-block;
    overflow: hidden;
    background: #ffffff;
}
.ldio-sn8z9znbf4c {
    width: 100%;
    height: 100%;
    position: relative;
    transform: translateZ(0) scale(0.56);
    backface-visibility: hidden;
    transform-origin: 0 0; /* see note above */
}
.ldio-sn8z9znbf4c div {
    box-sizing: content-box;
}
/* generated by https://loading.io/ */
</style>

